### ISSUE TITLE
Class 'WechatMiniProgram\WechatMiniProgram' not found

### ISSUE THREAD

**Issue by diguoyihao** [LuckyHJH/WechatMiniProgram#2]
我使用的的是tinkphp6框架，composer require luckyhjh/wechat-mini-program后使用方法发现类不存在

**Comment by LuckyHJH** [comment]
> 我使用的的是tinkphp6框架，composer require luckyhjh/wechat-mini-program后使用方法发现类不存在

以作兼容，更新到1.0.2即可
